### ISSUE TITLE
Sagamusix "atomic_playboy.it" doesn't play correctly

### ISSUE THREAD

**Issue by knight-ryu12** [libxmp/libxmp#145]
Wether it uses ~~OMPT specific hacks~~ or not, it doesn't play correctly.
(EDIT: It was somewhat obscure IT effect behavior)

1) Offset handling is buggy
"Am I a playboy" voice with offset doesn:t play correctly

2) Lower note doesn't trigger the voice

**Comment by sagamusix** [comment]
It doesn't use any OpenMPT-specific hacks, but it exploits IT's behaviour of portamento + offset on the same row.

**Comment by knight-ryu12** [comment]
seems like that is the case.
Hmm… wonder where the line is those behaivor critical source…

**Comment by knight-ryu12** [comment]
Maybe this can be referenced with recent IT commit?

**Comment by AliceLR** [comment]
This bug still exists as far as I can tell.

1) occurs at order 16h / pattern 9 and might be due to the initial note not having an offset but it's hard to tell because there's a bit going on there. A similar issue occurs in order 23h / pattern 24 and there's less going on (initial note there also lacks the offset).

2) occurs at order 19h / pattern 12 and is unrelated to portamento+offset abuse. The offender might be this (track 12, row 27h):
```
A-4 01 v00 ...
=== .. v54 ...
```

**Comment by AliceLR** [comment]
Relevant portion of read_event.c for the second bug: https://github.com/libxmp/libxmp/blob/master/src/read_event.c#L1312

The cited test is not completely silent in OpenMPT and I suspect it's silent in xmp for the wrong reason (row 4 should be quiet because of two inverted chip samples playing simultaneously, not because the volume should be ignored in that situation).

**Comment by AliceLR** [comment]
The bugs at order 19h / pattern 12 and order 23h / pattern 24 seem to be fixed with patch #239. This patch does nothing about the first bug, which needs more investigation (and possibly input from someone with a degree in obscure Impulse Tracker behavior).

**Comment by AliceLR** [comment]
Well, here's the first issue that needs to be resolved with IT sample sustain loops: xmp overwrites the regular loop with it (this track uses a small sustain loop to create instruments from a voice sample and uses a separate bidirectional main loop to repeat the full voice sample). https://github.com/libxmp/libxmp/blob/master/src/loaders/it_load.c#L740

**Comment by AliceLR** [comment]
Changing this line to `if (ev.note && !disabled_toneporta) {` fixes the order 16h / pattern 9 issue (disabled_toneporta is set when toneporta+offset is used). It seems like maybe it should also check for regular tone portamento usage here but I haven't thoroughly tested this yet. Can @sagamusix confirm this change would be roughly correct? https://github.com/libxmp/libxmp/blob/master/src/read_event.c#L1277

(This change slightly alters the mixer volume for the Off-Porta.it and breaks the last note of Off-Porta-CompatGxx.it, so it's not 100% correct.)

**Comment by AliceLR** [comment]
I made some test ITs for this and found another unrelated bug (it seems sometimes notes with high portamento values do not take effect as quickly in xmp as they do in IT 2.14—rows 6-14 should not "swing") but otherwise it should be fine for testing this. These ITs contain a single sample/instrument with 256 bytes of silence, a 32 byte square wave, and a 32 byte sawtooth. The square has a sustain loop and the two waveforms combined are the main loop. Every note after the first plays using the main loop in IT 2.14 and OpenMPT: [portamento_offset_after_keyoff.zip](https://github.com/libxmp/libxmp/files/5595333/portamento_offset_after_keyoff.zip)

The aforementioned "fix" on line 1083 fixes some but not all notes in these.

**Comment by knight-ryu12** [comment]
On my side, 2nd problem is fixed. one more to go...!

**Comment by AliceLR** [comment]
I still haven't had a chance to figure out the correct approach to fixing the first issue but it seems clear that the "minor tweaks" I was trying before weren't cutting it. I also ran into a separate issue while working on this that would affect any attempt to regression test the fix for the first problem (#242). I think that should be fixed first since 76 affected tests is already a lot to sift through...

**Comment by knight-ryu12** [comment]
I just checked #242, but it still have issues on first voice line

**Comment by knight-ryu12** [comment]
testing 4.5.0 release; Seems that pattern 16h(pattern 9)'s voiceline sounds off.

**Comment by AliceLR** [comment]
IIRC this was due to a conflict with regard to when/how the sustain loop is cancelled—it hasn't been patched yet nor have I figured out what the correct fix is, sorry.

**Comment by AliceLR** [comment]
This module sounds worse now with #510. This is due to #510 fixing some missing/broken sustain loop bounds checks in the mixer; this module was only *appearing* to work properly in some places because libxmp would just let it play wherever in the sample in spite of the sustain loop actually being active.

Hopefully *now* it's easier to verify whatever the correct fix for this thing is.

**Comment by AliceLR** [comment]
OK, identified which parts of this spaghetti that are relevant:

Line 997: `is_release` and `reset_env` are initially 0.
```C
	is_release = 0;
	reset_env = 0;
```
Line 1037: set `is_release` if `NOTE_RELEASE` is active, which it is in this case.
```C
	if (TEST_NOTE(NOTE_RELEASE | NOTE_FADEOUT)) {
		is_release = 1;
	}
```

Line 1057: if the instrument is set, set `reset_env`, except in a very specific case. If I had to guess, the bug starts here, because with legacy `Gxx` the sample sustain absolutely is *not* reset, but this unconditionally resets it.
```C
	if (ev.ins) {
		int ins = ev.ins - 1;
		int set_new_ins = 1;

...

		if (is_toneporta && xc->ins == ins) {
			if (!HAS_QUIRK(QUIRK_PRENV)) {
				if (is_same_sid(ctx, chn, ins, key - 1)) {
					/* same instrument and same sample */
					set_new_ins = !is_release;
				} else {
					/* same instrument, different sample */
					not_same_ins = 1; /* need this too */
					not_same_smp = 1;
				}
			}
		}

		if (set_new_ins) {
			SET(NEW_INS);
			use_ins_vol = 1;
			reset_env = 1;
		}
```

Side note: `reset_env` gets cleared if a new note is set if it's `XMP_KEY_OFF` or `XMP_KEY_FADE`.

Line 1177: in some cases a regular note will also set `reset_env`, though this didn't seem to be the primary source of it getting set.
```C
			/* portamento_after_keyoff.it test case */
			/* also see suburban_streets o13 c45 */
			if (ev.ins || !is_toneporta) {
				if (!disabled_toneporta) {
					reset_env = 1;
				}
			}
```

Side note: at 1282, `reset_env` can be cleared dependent on the current fadeout state, which doesn't seem to be relevant here.

Line 1290: if `reset_env` is set, clear `NOTE_RELEASE`, which resets both the envelope sustain and the sample sustain.
```C
	if (reset_env) {
		if (ev.note) {
			RESET_NOTE(NOTE_RELEASE|NOTE_SUSEXIT|NOTE_FADEOUT);
		}
		/* Set after copying to new virtual channel (see ambio.it) */
		xc->fadeout = 0x10000;
	}
```

**Comment by AliceLR** [comment]
Found one bug, anyway: libxmp releases both the envelope and sample sustain when ANY note with an instrument or portamento is encountered, unless that portamento was "canceled" by `Oxx`. See line 1177 in the previous post. The bug here is the check for `ev.ins` is both totally irrelevant (it sets `reset_env` elsewhere) and breaks the check for portamento. This actually should have been caught by Fade-Porta.it but I guess someone didn't look at the levels in Impulse Tracker : )

This module still doesn't play right, but it's definitely part of the problem (two of the notes in the cited part of order 16h use portamento with an instrument number and no `Oxx`).

**Comment by AliceLR** [comment]
From a *very small* amount of experimentation it seems that the only further change required should be this: when the same instrument is encountered, only reset the sample sustain loop if there is *not* tone portamento. Relevant section of code is the end of that line 1057 snippet.

I still need to check this against things like invalid samples and different subinstruments to make sure `reset_susloop` gets set in the correct spot, but it seems clear that it should *not* be set with `reset_env` there. So, this seems to confirm that envelope release and sample sustain release *do* need to be separate channel flags.

**Comment by AliceLR** [comment]
Testing various edge cases—I found an interesting one where, in Impulse Tracker, this construct actually preserves sustain release through all three notes in sample mode (Instrument Mode not tested yet):

[SUSPRT_S.IT.zip](https://github.com/libxmp/libxmp/files/7949763/SUSPRT_S.IT.zip) (actual occurrence in the module is rows 32-47)
```
ModPlug Tracker  IT
|C-401......
|===........
|D#402g05...
|E-401g05...
```

OpenMPT seems to get this one wrong... the second note is silent due to having a 1 sample sustain loop, and the final note has active sustain.

**Comment by sagamusix** [comment]
🙈

**Comment by sagamusix** [comment]
I think I have a viable bugfix for this testcase for OpenMPT, but this changes such a central piece of the playback routines that I first want to finish my automated test suite before fixing this :(

**Comment by AliceLR** [comment]
Delay in getting the final patch for this was due to libmodplug activity and also I found *another* bug here, but it's one that doesn't need a separate patch. Thanks to non-zero `ev.ins` allowing an envelope reset at line 1177, the fadeout level was getting reset every time a new note with both portamento and offset is played, causing a slight variation in volume in the last note of Off-Porta.it. By removing that condition for resetting the envelope and removing "disabled" toneporta I ended up fixing this completely by accident...

> I think I have a viable bugfix for this testcase for OpenMPT, but this changes such a central piece of the playback routines that I first want to finish my automated test suite before fixing this :(

Considering no one noticed it it's probably not *that* much of a priority... it might be useful for approximating PWM with a built-in decay or something.

**Comment by AliceLR** [comment]
Uhhh, another one which OpenMPT seems to do correctly: when SampleNumberChange.it is modified to have a keyoff before the sample changes, sample 99 doesn't cut the current note. libxmp gets this wrong...

**Comment by AliceLR** [comment]
> By removing that condition for resetting the envelope and removing "disabled" toneporta I ended up fixing this completely by accident...

except now "am I a playboy?" is completely silent, but when I make a module of just that, it isn't. I feel like if I keep digging I'm going to somehow find OctaMED
