### ISSUE TITLE
Several Pha Packer test modules fail to load.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#277]
Split from the comments of #266—several of the PHA ProPacker test files linked in the comments for that PR do not load. Whatever the issue is, I was able to reproduce it building from a commit from several years ago, so it's not a new bug.

[ProPacker examples (PHA).zip](https://github.com/libxmp/libxmp/files/5773084/ProPacker.examples.PHA.zip)

**Comment by AliceLR** [comment]
Update on this: the file that does load (Glamorous Gennie 62 menu) has a truncated pattern compared to the MOD [here](http://janeway.exotica.org.uk/release.php?id=76714).

**Comment by AliceLR** [comment]
This was caused due to the loader relying on reading a truncated block from the input file without clearing the error/EOF flag (presumably fseek/hio_seek previously did this at one point in the past).

**Comment by AsleAMP** [comment]
Following your remark about truncated file, I've checked them all again
-> PHA file is fine and 100% identical to what can be found in the packdisk menu you point out.
-> the MOD original files are not truncated either
-> PHA and MODs match 99% (the 400 are replaced with 4** in the PHA but that doesn't affect the replay).

Can you please elaborate around this notion of "truncated" notion, please ? I'm afraid I don't understand.

----- Mail original -----
De: "Alice R." <notifications@github.com>
À: "libxmp/libxmp" <libxmp@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Vendredi 8 Janvier 2021 11:13:38
Objet: Re: [libxmp/libxmp] Several Pha Packer test modules fail to load. (#277)





This was caused due to the loader relying on reading a truncated block from the input file without clearing the error/EOF flag (presumably fseek/hio_seek previously did this at one point in the past).

**Comment by AliceLR** [comment]
Specifically I mean that, when xmp plays it back, pattern 2's data abruptly ends in the Pha version of the module starting around row 28, and the previous notes hold for the rest of the pattern (as if the pattern data has been truncated). The MOD version of this (anarchymenu 08.mod) does not have the same issue in xmp. I don't know what that actual cause of this is yet.

I will check to make sure it isn't an issue with my local copy of the file too, since that's the only file I encountered this with.

**Comment by AliceLR** [comment]
Alright, I've got the issue: the pattern data is being truncated by the sketchy method libxmp uses to read the pattern data into memory. It loads `index of highest pattern * 1024` bytes into RAM, which works out to 2048 bytes for that module (which is insufficient).

**Comment by AliceLR** [comment]
(To be clear, #289 fixed both the EOF flag issue and the pattern truncation issue.)
