### ISSUE TITLE
DoS (and smaller leaks) revealed by AFL++, batch 2

### ISSUE THREAD

**Issue by debrouxl** [libxmp/libxmp#301]
The fourth afl-fuzz instance I started recently for #299 is also doing much better with hangs or excessive memory consumption, thanks to #295 :)
However, it has started producing new samples whose behaviour is an outlier for both loading time - which is the proximate cause of afl-fuzz saving them - and memory consumption - which is closer to the ultimate cause of probably missing more sanity checks. The OOM killer correctly takes care of ASAN-instrumented libxmp+xmp within a few seconds of these samples markedly degrading system performance, at a point they already consume more than 4 GB of RAM... so beware, even though the consumption of a non-instrumented build should be smaller ;)
Years ago, I remember openmpt consuming more than 5 GB of RAM and seconds of CPU time loading a specially crafted sample, before getting killed by the OOM killer.

Also, the ASAN-instrumented build reports that 3 of these new samples, so far, cause 2 different memory leaks; I went looking in the logs, and found 2 older samples which cause the same memory leak when loading a specially crafted Scream Tracker 1.10 module:
```
Loading output/2/hangs/id:000172,src:019399,time:3986356923,op:havoc,rep:4 (1 of 1)
Module name  : Noname
Module type  : Scream Tracker 1.10
Module length: 0 patterns
Patterns     : 257
Instruments  : 32
Samples      : 32
Channels     : 4 [ 4 b b 4 ]
Duration     : 0min00s

=================================================================
==3843688==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1264640 byte(s) in 63232 object(s) allocated from:
    #0 0x49a862 in calloc (.../bin/xmp+0x49a862)
    #1 0x7fb08b89eea0 in libxmp_alloc_pattern .../xmp/libxmp/src/loaders/common.c:110:18
    #2 0x7fb08b89eea0 in libxmp_alloc_pattern_tracks .../xmp/libxmp/src/loaders/common.c:158:6

SUMMARY: AddressSanitizer: 1264640 byte(s) leaked in 63232 allocation(s).
```

The other leak is:
```
Loading output/4/hangs/id:000023,src:001184,time:126933623,op:havoc,rep:4 (1 of 1)
.../bin/xmp: output/4/hangs/id:000023,src:001184,time:126933623,op:havoc,rep:4: Error loading module

=================================================================
==3899276==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2401408 byte(s) in 5 object(s) allocated from:
    #0 0x49a862 in calloc (.../bin/xmp+0x49a862)
    #1 0x7f4e560044b4 in libxmp_alloc_subinstrument .../xmp/libxmp/src/loaders/common.c:84:20

SUMMARY: AddressSanitizer: 2401408 byte(s) leaked in 5 allocation(s).
```

[xmp_remaining_hangs_20210118_1100.tar.gz](https://github.com/libxmp/libxmp/files/5829546/xmp_remaining_hangs_20210118_1100.tar.gz)

[xmp_memory_leaks_20210118_1108.tar.gz](https://github.com/libxmp/libxmp/files/5829548/xmp_memory_leaks_20210118_1108.tar.gz)

EDIT: note that the tests have been performed with the patch from #300 manually applied.

**Comment by AliceLR** [comment]
I've looked into the STM leak and found that the slowdown is due to the pattern field not being validated, causing 63489 patterns to be allocated from EOFs. However, the cause of the leak is this unwise attempt to cap the pattern count in libxmp_load_epilogue:
```
(gdb) c
Continuing.

Thread 1 "xmp" hit Hardware watchpoint 2: ((struct context_data *)xc)->m.mod.pat

Old value = 63489
New value = 257
0x00007ffff7dc5bdf in libxmp_load_epilogue (ctx=0x625000000100) at src/load_helpers.c:257
257		CLAMP(mod->pat, 0, 257);   /* some formats have an extra pattern */
```
These CLAMPs are a bad idea exactly because of situations like this.

**Comment by debrouxl** [comment]
Updated kills tarball: [xmp_remaining_hangs_20210120_1110.tar.gz](https://github.com/libxmp/libxmp/files/5841604/xmp_remaining_hangs_20210120_1110.tar.gz) .
No new leaks since two days ago when sifting through the set of (former) "hangs".

**Comment by AliceLR** [comment]
The GAL5 loader leak was another instance of duplicate instruments. Progress here: https://github.com/libxmp/libxmp/compare/master...AliceLR:fix-fuzzing-hangs-2

All of the leaks from this batch should be fixed now. Will check out the hangs soon.

**Comment by AliceLR** [comment]
I've taken a quick look through the hangs to categorize them to make this easier.
```
2/000070: vorbis.c start_decoder (residue classifications)
2/000080: sample.c convert_signal
2/000150: sample.c convert_signal
4/000000: sample.c convert_signal
4/000002: sample.c convert_signal
4/000003: sample.c __memset_avx2_unaligned_erms (!)
4/000004: sample.c __memset_avx2_unaligned_erms (!)
4/000005: sample.c __memset_avx2_unaligned_erms (!)
4/000006: sample.c __memset_avx2_unaligned_erms (!)
4/000013: vorbis.c start_decoder (codebooks)
4/000014: vorbis.c start_decoder (residue classifications)
4/000019: sample.c convert_signal
```
Both types of sample.c inputs also consume all of the RAM in the VM I've been using for sanitizer testing. Wow!

The vorbis hangs are due to missing EOF checks in various places in start_decoder, so some absurdly high values earlier in the stream cause it to loop for a long time without realizing it's at the end of the stream. Patch for those should be up soon.

**Comment by AliceLR** [comment]
Both sample.c bugs were due to a case I didn't fix but thought might happen: invalid sample sizes but with a valid sample start location. These samples now get truncated before any allocation or reading occurs.

**Comment by debrouxl** [comment]
Good. Some existing malformed modules produced by a buggy tracker might become rejected by libxmp after adding these checks, but it's probably better than triggering (quasi-)unbounded memory consumption on user computers, which can have significant DoS effects.

**Comment by AliceLR** [comment]
The samples patch won't reject those types of modules outright, but it will definitely alter the length (and potentially looping properties) of the particular affected samples.

**Comment by AliceLR** [comment]
Note that I still need to fix some issues associated with this batch that were posted in the above issue. Copying the link here: https://github.com/libxmp/libxmp/files/5860029/xmp_higher_ram_consumption_20210123_1122.tar.gz

**Comment by AliceLR** [comment]
The remaining issues to fix are distributed across the following locations:
```
LHA depacker:
	3/000105

Digital Tracker loader:
	2/000131
	3/000090
	4/000028

Impulse Tracker loader:
	3/000051
	4/000015
	4/000016
	4/000018
	4/000020
	4/000022
	4/000025
	4/000031

MDL loader:
	2/000092
	2/000102
	4/000026
```

Since https://github.com/libxmp/libxmp/compare/master...AliceLR:prowizard-fuzzing-fixes-5 already has a Digital Tracker patch and the crashes are currently slowly trickling in I'll probably address these in that branch.

**Comment by AliceLR** [comment]
The LHA test file creates a 76 MB "ProTracker module" in /tmp. 7-Zip detects that this file is invalid but I'm not sure exactly how it figures out (not familiar with the LHA format). The bulk of this 76 MB and the slowness comes from `decode_c_st1` directing the depacker to write large blocks of 0s that each consume 0 bits from the bitstream.

**Comment by AliceLR** [comment]
The hanging/RAM consumption in the Digital Tracker loader was from a missing channel count bounds check trying to allocate several patterns with >65000 tracks each.

**Comment by AliceLR** [comment]
The hanging/RAM consumption in the MDL loader was due to a buffer for sample data being allocated without any sanity checks occurring first. Bounding checks are now done on the projected packed sample size and invalid sample packing types before any (re)allocation is done for the sample. Relatedly, the same temporary buffer is now reused for every sample instead of doing an extra calloc and free for every sample.

**Comment by AliceLR** [comment]
The hanging/RAM consumption in the IT loader is due to the loader allocating a buffer for compressed samples without a sanity check on the size. It turns out the lower bound for compressed sample sizes is 1/8th the size of the sample (in samples) so this fix is straightforward, but I want to do more testing on it first to make sure nothing breaks.

**Comment by debrouxl** [comment]
Indeed, IT is one of the major formats.

**Comment by AliceLR** [comment]
I did find a handful of IT modules with truncated samples (9 out of a pool of 22k...) and adjusted the behavior to shrink the affected samples instead of rejecting them. With the revised patch only 2 of those 9 modules are rejected due to pattern truncation. I'm going to run `xmp --load-only` on the entire ModLand IT collection again but I think this patch is probably OK.

**Comment by AliceLR** [comment]
The latest run of `xmp --load-only` resulted in only 44 total load failures. Of those, 3 (including the aforementioned modules) are from pattern scan errors, 36 fail due to `bad instrument magic`, 1 fails due to an unknown issue loading an instrument, 1 fails due to a sample magic mismatch, 2 fail due to >255 samples (which should be valid, but whatever), and 1 fails due to having an invalid size on an unused instrument (fixed in my patch). More revisions may be required but I think this particular patch is done.

**Comment by AliceLR** [comment]
I've patched the LHA issue, which was the last bug remaining from the new batch. I'm not sure I implemented the correct solution but I'll go ahead and start a PR to get these patches reviewed.
