### ISSUE TITLE
The problem of using the Libxmp in NehQuake 3.08

### ISSUE THREAD

**Issue by Alex3474247** [libxmp/libxmp#314]
First of all, I've learned the libxmp api and some samples here: http://xmp.sourceforge.net/libxmp.html
And of course, the quakespasm code at sourceforge, however it is not suitable for me, most of the functions differs significantly.
The MSVC 6.0 debugger showed that libxmp return codes are 0 everywhere, so everything seems to be ok, but it is not, no music in game (in neh1m1 level the neh4.xm mod should play, but silence).
Firstly I downloaded it from https://www.quaddicted.com/files/engines/nehsrc254.zip, then from http://bjp.fov120.com/nehquakebjp.zip , then merged these 2 source codes and added all missing files to the dsp project. Then compiled it in 2014 on a windows XP machine. And everything went fine, music was playing, but fmod is evil, non-modern(2001) and proprietary... I have to remove it from Nehahra and replace it with something modern, like libxmp! 
Here is my modified neh.c source file:

[neh.txt](https://github.com/libxmp/libxmp/files/5996338/neh.txt)
Please help me somebody if anyone can!

**Comment by sezero** [comment]
First: this is _not_ the place for quake source issues. Your issue is about
working with quake source, not libxmp api.  Therefore closing this.

About your issue:  I had a _very_ brief look at your source. From what I
understand, the old code use `fmod`: As far as I know, `fmod` opens the
sound device and creates its own thread for playback. The libxmp api has
nothing of the likes. I.e.: You need to feed the samples you retrieve from
libxmp to quake's snddma engine. For that we backported S_RawSamples
from quake2 to quakespasm: that's how all music stuff works in uhexen2
and quakespasm.
