### ISSUE TITLE
make the library MIT-licensed?

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#387]
> The majority of libxmp files is MIT, but the library itself is LGPL because there are a few third party components (unzip, etc) that are LGPL. The "lite" library version uses only MIT-licensed sources so the entire library can be released under the MIT license, which is more permissive (but the "lite" version doesn't include prowizard-pc files). ...

For what it's worth, I went through the libxmp files to figure out what is actualy LGPL vs. MIT, and in the case of `--disable-depackers` only *one* active loader actually pulls in LGPL code (Digital Symphony pulls in the LGPL LZW depacker, but since this loader needs attention anyway #347, I've thought about just writing it a new sample depacker). So if the depackers do get separated to a second library, it's very possible the entirety of libxmp could be placed under the MIT license. The remaining LGPL code:

* `fmopl.c`— currently deadcode. If OPL support gets readded for e.g. S3Ms, a bugfixed Opal might be a suitable replacement. Opal (public domain) is the RAD v2 OPL3 emulator, and is used by OpenMPT and other projects.
* `fcm_load.c`, `ftm_load.c`, `hvl_load.c`, `polly_load.c`, `ssmt_load.c`, `stc_load.c` are all deadcode right now.

Also, thanks for clarifying ProWizard's licensing. :)

_Originally posted by @AliceLR in https://github.com/libxmp/libxmp/issues/214#issuecomment-856268075_

**Comment by sezero** [comment]
I guess this requires ditching the depackers (in some way) and the particular dead
code listed above, and adopting a suitably licensed lzw depacker for `sym_load.c`.

**Comment by sezero** [comment]
About  lzw depacker for `sym_load.c`: [liblzw](https://github.com/vapier/liblzw) (under unlicense) maybe?

**Comment by AliceLR** [comment]
A more thorough breakdown:

* The affected loaders might just as well be relicensed (or replaced if it comes to it).
  * `fcm_load.c` predates the Git repository. ProWizard supports this format so this can probably be junked.
  * `ftm_load.c` predates the Git repository.
  * `hvl_load.c` was [added in 2010](https://github.com/libxmp/libxmp/commit/37ff3c88e79475dd3b78070f10fe46d2fcdaff5a).
  * `polly_load.c` was [added in 2010](https://github.com/libxmp/libxmp/commit/58a467a6b82c543e5a8f92a4618c7f9d943dc305).
  * `ssmt_load.c` was [added in 2007](https://github.com/libxmp/libxmp/commit/4b27e63f2e9a0fd4d72601b4c49cd6e295e403b7).
  * `stc_load.c` was [added in 2011](https://github.com/libxmp/libxmp/commit/10f92ec9f707fdef2ef893a388d79a39e81c60b4).

* Depackers: @cmatsuoka has indicated before that he wants to split depackers to a separate library. Some depackers will probably need custom attention if this happens.
  * Digital Symphony: I'm not familiar with liblzw. Digital Symphony uses its own weird variant of LZW (#347) so I was considering just writing my own implementation when I get around to addressing that format.
  * Galaxy Music System: these use a custom DEFLATE-based "MUSE" container. It may or may not be worth keeping this depacker inside of libxmp. The inflate implementation is LGPL.
  * OXM: IMO stb-vorbis should be pulled into the non-lite sample code if possible instead of treating this like a depacker.

* `fmopl.c`: get rid of it. Since S3Ms apparently never supported drum mode anyway and OpenMPT has no intention of adding it to MPTM (because drum mode is terrible), a bugfixed Opal should be sufficient as-is if support is added. Let AdPlug handle dedicated OPL formats.

**Comment by sezero** [comment]
> A more thorough breakdown:
> 
>     * The affected loaders might just as well be relicensed (or replaced if it comes to it).
>       
>       * `fcm_load.c` predates the Git repository. ProWizard supports this format so this can probably be junked.
>       * `ftm_load.c` predates the Git repository. (Also, it's not even close to finished.)
>       * `hvl_load.c` was [added in 2010](https://github.com/libxmp/libxmp/commit/37ff3c88e79475dd3b78070f10fe46d2fcdaff5a).
>       * `polly_load.c` was [added in 2010](https://github.com/libxmp/libxmp/commit/58a467a6b82c543e5a8f92a4618c7f9d943dc305).
>       * `ssmt_load.c` was [added in 2007](https://github.com/libxmp/libxmp/commit/4b27e63f2e9a0fd4d72601b4c49cd6e295e403b7).
>       * `stc_load.c` was [added in 2011](https://github.com/libxmp/libxmp/commit/10f92ec9f707fdef2ef893a388d79a39e81c60b4).

Good thing about these ones is that they are not packaged with releases

**Comment by sagamusix** [comment]
For deflate, zlib or [miniz](https://github.com/richgel999/miniz) (single-file drop-in replacement for zlib) could be used. As miniz is a drop-in replacement, this could also make packagers on Linux happy because it would mean that xmp could be linked against zlib there, but the repository could still contain miniz as a fallback for ease of use.

For OPL, note that finally there is another permissively-licensed emulator available since recently, in addition to Opal: https://github.com/aaronsgiles/ymfm

**Comment by AliceLR** [comment]
> https://github.com/aaronsgiles/ymfm

I was made aware of this a while ago to evaluate as a potential Opal substitute for MegaZeux's RAD support, but haven't checked it out yet. Both ymfm and Opal are C++, which doesn't really mesh with what libxmp is trying to do, but at the very least Opal should be fairly portable.

As a side note, something interesting I found in Opal: its built-in linear resampler is SLOW (emits a bunch of IDIVs or worse). I wrote a non-intrusive wrapper to bypass it that might be useful if libxmp ever picks it up:
```C++
#define OPL_FREQUENCY 49716

class FastOpal : public Opal
{
public:
  FastOpal() : Opal(OPL_FREQUENCY) {}

  /**
   * This skips Opal's built-in linear resampler. The built-in resampler uses
   * integer division, which is slow, particularly on platforms like the 3DS
   * that lack an integer division instruction. This means that the output will
   * always be 49716Hz and thus needs resampling (which still should be faster).
   */
  void Sample(int16_t *left, int16_t *right)
  {
    Output(*left, *right);
  }
};
```

**Comment by AliceLR** [comment]
Claudio hasn't commented on this yet but this commit message suggests that migration to MIT is explicitly a goal of his. https://github.com/libxmp/libxmp/commit/ac1f777e007e81cb184fc0791670211634fb2adc

**Comment by sezero** [comment]
> Claudio hasn't commented on this yet but this commit message suggests that migration to MIT is explicitly a goal of his. [ac1f777](https://github.com/libxmp/libxmp/commit/ac1f777e007e81cb184fc0791670211634fb2adc)

Oh yes !

**Comment by sezero** [comment]
We should cure the `sym_load` case in some way: it's the only one that pulls
in lgpl code when depackers are disabled, yes?

As I understand, `gal[4|5]_load` code don't pull in any lgpl code, but without
`muse` they are non-functional?

**Comment by AliceLR** [comment]
> We should cure the `sym_load` case in some way: it's the only one that pulls
> in lgpl code when depackers are disabled, yes?

Yes. After reviewing the LZW depacking code it seems tailored with numerous hacks specifically towards accommodating the specific LZW used in the ARC/ArcFS formats, and Claudio had to disable numerous of these to get it to work for Digital Symphony. I think I'm going to go ahead with writing a LZW sample decoder for this loader, since another problem with it is it bizarrely requires the module to be loaded from FILE to work (despite the LZW decoding occurring entirely in memory).

> As I understand, `gal[4|5]_load` code don't pull in any lgpl code, but without
> `muse` they are non-functional?

Correct.

**Comment by AliceLR** [comment]
Progress on writing a new LZW depacker for Digital Symphony here: https://github.com/libxmp/libxmp/compare/master...AliceLR:symphony-lzw

This is a pared down and relicensed version of a ZIP UnShrink algorithm I previously wrote. I'll post an update once I get it actually working... :)

**Comment by AliceLR** [comment]
Pinned this so it doesn't keep getting buried.

Progress on this that's been made since the last update:

* Digital Symphony: #439
* Zip/gzip/MUSE: #436

**Comment by AliceLR** [comment]
All of the depackers that are still LGPL since I didn't do that last time for some reason:

* Nomarch (replacement planned for soon-ish):
  * arcfs.c
  * readhuff.{c,h}
  * readlzw.{c,h}
  * readrle.{c,h}
  * unarc.c
* bunzip2.c
* XAD:
  * unlha.c
  * unlzw.c
* XFD bindings for AmigaOS:
  * xfd.c
  * xfd_link.c
* xz (GLUE CODE ONLY). The depacker itself is public domain, so why is the glue code LGPL?

**Comment by AliceLR** [comment]
XZ is now entirely PD and MIT: https://github.com/libxmp/libxmp/pull/522

**Comment by sezero** [comment]
gunzip: Do we _know why_ gunzip.c is actually LPGL? The original file had
no license or copyright notice.

bunzip2: What we have is clearly LGPL. However, later versions of it are
under the 0BSD license: https://www.landley.net/code/
http://landley.net/hg/toybox/log/37ea9dff9c27/lib/bunzip.c
https://www.landley.net/toybox/license.html
.. so: maybe we can migrate to it, assuming it is compatible
to our use?

Amiga xfd: Well, hell.. Do we even need this?

Rar (the fork to unrar): Remove, really?

**Comment by AliceLR** [comment]
My C adaptation of the ArcFS handling is pretty much ready for libxmp, but I'd like to finish ARC/Spark too before opening a pull request. (It's not that much more effort, Spark just has really annoying nested archive subdirectories instead of the nice flat list ArcFS does.)

Digging around for LHA and LZX information now. Microsoft has [documentation on LZX *compression*](https://docs.microsoft.com/en-us/previous-versions/bb417343(v=msdn.10)?redirectedfrom=MSDN#microsoft-lzx-data-compression-format) since it's used in CAB files, but I haven't seen any notes about the container format itself. Lots of (L)GPL implementations of it but that's about it. The original LHA has a permissive license *apparently*, and [the source](https://github.com/jca02266/lha) is around, but all of the documentation and license info is in Japanese.

> gunzip: Do we _know why_ gunzip.c is actually LPGL? The original file had no license or copyright notice.

I have no clue. It should be pretty trivial to just rewrite the glue code...

> bunzip2: What we have is clearly LGPL. However, later versions of it are under the 0BSD license: https://www.landley.net/code/ http://landley.net/hg/toybox/log/37ea9dff9c27/lib/bunzip.c https://www.landley.net/toybox/license.html .. so: maybe we can migrate to it, assuming it is compatible to our use?

The [bunzip2 implementation](http://www.sourceware.org/bzip2/downloads.html) from the original author is BSD-4 (updated in 2019), which I *think* would be in the clear as long as it's noted in docs/CREDITS? The 0BSD reimplementation in Toybox also looks promising.

> Amiga xfd: Well, hell.. Do we even need this?

I'm not familiar enough with xfd or Amiga crunchers in general to have an answer to this.

> Rar (the fork to unrar): Remove, really?

I think unfortunately RARs still get used :(

**Comment by sagamusix** [comment]
One could argue that a RAR decoder really shouldn't be part of libxmp (just like all other generic decompression routines). Maybe instead of removing them entirely, they could be moved to a complementary library with the next major version bump that is easy to use together with libxmp but has a less permissive license?

**Comment by AliceLR** [comment]
> One could argue that a RAR decoder really shouldn't be

well, yes

> part of libxmp (just like all other generic decompression routines).

I don't think the generic depackers are actually hurting anything by existing as long as they aren't too bloated and aren't vulnerabilities and aren't polluting users with a bunch of temporary files. I did propose a compile time option for a reduced subset of depackers here: [https://github.com/libxmp/libxmp/issues/506#issuecomment-1002443680]

There also isn't a clear cut line for some of them—ARC/ArcFS/Spark are "general" depackers but they are widely used for RISC OS modules and support for them isn't as common as ZIP or even LHA. And [PowerPacker](https://github.com/OpenMPT/openmpt/blob/master/soundlib/ContainerPP20.cpp) is technically a general compression format...

> Maybe instead of removing them entirely, they could be moved to a complementary library with the next major version bump that is easy to use together with libxmp but has a less permissive license?

Assuming "them" is specifically XFD and RAR here—maybe. RAR doesn't have a license problem right now so much as one where it's an external command invoked with `CreateProcess` / `exec`+`fork` and probably vulnerable to path injection (not to mention the very edge case platforms that still need `popen`... yikes). I don't know, since XFD is Amiga-only *maybe* there could be a disclaimer somewhere that Amiga builds have to be LGPL still after everything else gets replaced.

Claudio has mentioned the idea of splitting the depackers off before but considering how busy he is, big changes like that or any major version bump in general seem kind of theoretical at this point.

**Comment by sezero** [comment]
> My C adaptation of the ArcFS extractor is pretty much ready for libxmp, but I'd like to finish ARC/Spark too before opening a pull request. (It's not that much more effort, Spark just has really annoying nested archive subdirectories instead of the nice flat list ArcFS does.)

This will be a valuable addition when finished

> > gunzip: Do we _know why_ gunzip.c is actually LPGL? The original file had no license or copyright notice.
> 
> I have no clue. Worst case, it should be pretty trivial to just rewrite the glue code...

This commit is the guilty one: https://github.com/libxmp/libxmp/commit/f26ccdb463686fbf760e5be9c18572d34fe6c66c
It added LGPL header to practically all srcs that lacked one,
and _not_ just to depacker srcs.  So, I _suspect_ gunzip can
easily be relicensed, possibly xfd as well

> The [bunzip2 implementation](http://www.sourceware.org/bzip2/downloads.html) from the original author is BSD-4 (updated in 2019), which I _think_ would be in the clear as long as it's noted in docs/CREDITS? The 0BSD reimplementation in Toybox also looks promising.

The 0BSD one is an iteration of what we already have, that's why I
mentioned it only.

> > Amiga xfd: Well, hell.. Do we even need this?
> 
> I'm not familiar enough with xfd or Amiga crunchers in general to have an answer to this.

At the very least, its LGPL enforcement is questionable (see above.)
If only Chris Young could be contacted

> > Rar (the fork to unrar): Remove, really?
> 
> I think unfortunately RARs still get used :(

For compressing mods?

**Comment by AliceLR** [comment]
> This commit is the guilty one: [f26ccdb](https://github.com/libxmp/libxmp/commit/f26ccdb463686fbf760e5be9c18572d34fe6c66c) It added LGPL header to practically all srcs that lacked one, and _not_ just to depacker srcs. So, I _suspect_ gunzip can easily be relicensed, possibly xfd as well

> At the very least, its LGPL enforcement is questionable (see above.) If only Chris Young could be contacted

I can't imagine there's an issue with gunzip.c but xfd.c might still be problematic: it was added with an explicit copyright and the project license at the time was GPL 2+, so IMO there's a strong possibility this was intended. Is this a ported SVN commit or a patch Claudio received through email?  https://github.com/libxmp/libxmp/commit/951a240d0201e8e1ef375bcda2d22bb3bb5c29c0

> The 0BSD one is an iteration of what we already have, that's why I mentioned it only.

OK. It seems reasonable. I don't see any reason we can't go with it.

> For compressing mods?

I don't have any knowledge of this but for all I know yes. I've seem people pack anything and everything in them.  guess they really love their neverending 40-day free trials or never found out about 7zip

All things considered RAR requires a utility most distros don't ship by default to be on PATH and I don't know if anyone is seriously relying on that depacker. UnMO3 *seems* much more likely to be relied on because it adds support for an entire format, not an archiver the Internet should have dropped like it was hot 10 years ago.

IMO do nothing about either until after 4.5.1 is out. MO3 is too big of a project to shoehorn into a release that's already getting kind of bloated, and in the off chance anyone relies on RAR, it'd be nice if they can get this release's stability fixes.

**Comment by sezero** [comment]
> I can't imagine there's an issue with gunzip.c but xfd.c might still be problematic: it was added with an explicit copyright and the project license at the time was GPL 2+, so IMO there's a strong possibility this was intended. Is this a ported SVN commit or a patch Claudio received through email? [951a240](https://github.com/libxmp/libxmp/commit/951a240d0201e8e1ef375bcda2d22bb3bb5c29c0)

Mystery to me

**Comment by sezero** [comment]
> > The 0BSD one is an iteration of what we already have, that's why I mentioned it only.
> 
> OK. It seems reasonable. I don't see any reason we can't go with it.

Attaching here the bunzip.c file retrieved from the above hg link and its
license notice inserted into:  [bunzip.c.zip](https://github.com/libxmp/libxmp/files/7791530/bunzip.c.zip)

**Comment by sezero** [comment]
> Digging around for LHA and LZX information now. Microsoft has [documentation on LZX _compression_](https://docs.microsoft.com/en-us/previous-versions/bb417343(v=msdn.10)?redirectedfrom=MSDN#microsoft-lzx-data-compression-format) since it's used in CAB files, but I haven't seen any notes about the container format itself. Lots of (L)GPL implementations of it but that's about it. The original LHA has a permissive license _apparently_, and [the source](https://github.com/jca02266/lha) is around, but all of the documentation and license info is in Japanese.

Maybe this may help: https://github.com/fragglet/lhasa

**Comment by AliceLR** [comment]
Nice find with the LHA depacker, I will check it out when I'm less buried in f!^#!& ARC/ArcFS/Spark/PAK/ARC+/whatever else this ancient thing is called. I looked into ARC 6 (also used by ARC+ aka ARC 7) subdirectories and they're pretty much identical to Spark subdirectories so I added support for them. Support for subdirectories in general and skipping unrecognized things should be much better than in the nomarch code. Right now I'm fuzzing my code and testing some alternate bits of code for the bitstream (the old one kind of sucks).

(Also no I'm not adding support for unpacking PAK/ARC+ unless they're found used for modules in the wild somewhere. They both have different method 10s and you detect the difference by looking for a type 20 archive info record in ARC+ and/or method 11 compression in PAK and/or just brute forcing both method 10s and I didn't implement any of these depackers oh well 🥴)

Dropping my nomarch bugfix patch and testing tool here because I'll probably accidentally clobber it at some point and it's good for reference. The patch fixes compression methods 3 and 4 so a performance/binary size comparison will be remotely fair. Method 3 appears several times in the ArcadeBBS dump and method 4 appears exactly once. https://gist.github.com/AliceLR/f5a27814995c59ec8c8b03ee328fb3e6

**Comment by ccawley2011** [comment]
>>> Amiga xfd: Well, hell.. Do we even need this?
>>
>> I'm not familiar enough with xfd or Amiga crunchers in general to have an answer to this.
>
> At the very least, its LGPL enforcement is questionable (see above.)
If only Chris Young could be contacted

I'm fairly certain that @chris-y is the same Chris Young, so it's probably worth asking about this.

**Comment by chris-y** [comment]
> >>> Amiga xfd: Well, hell.. Do we even need this?
> >>
> >> I'm not familiar enough with xfd or Amiga crunchers in general to have an answer to this.
> >
> > At the very least, its LGPL enforcement is questionable (see above.)
> If only Chris Young could be contacted
> 
> I'm fairly certain that @chris-y is the same Chris Young, so it's probably worth asking about this.
> 

Happy new year!

I vaguely recall writing this. I'm happy for it to be relicensed under MIT if that is what is being asked.

As for whether it is required. Well... most modules use one of the common crunchers that libxmp supports, however things like OctaMED will crunch as any XPK library, and there are loads of obscure crunchers on the Amiga that are used for modules. XFD supports pretty much everything so on an Amiga it's extremely useful as a fallback when the file would otherwise be unidentified.

**Comment by AliceLR** [comment]
> Happy new year!
> 
> I vaguely recall writing this. I'm happy for it to be relicensed under MIT if that is what is being asked.

Hi! Yes, that would be fantastic, thank you! We weren't sure how to find you (thanks @ccawley2011!). I've opened a pull request for relicensing the XFD depacker here: #534.

> As for whether it is required. Well... most modules use one of the common crunchers that libxmp supports, however things like OctaMED will crunch as any XPK library, and there are loads of obscure crunchers on the Amiga that are used for modules. XFD supports pretty much everything so on an Amiga it's extremely useful as a fallback when the file would otherwise be unidentified.

That's *about* what I expected. libxmp has dedicated depackers for the usual crunchers + uses Asle's ProWizard port to pick up quite a few more MOD-specific crunchers, but these are probably only scratching the surface.

**Comment by AliceLR** [comment]
The ARC/ArcFS replacement is in now:
* #540

That leaves:
* bunzip2: in progress.
* gunzip glue code:
* LHA: see the above repository link.
* LZX: guess I'll get to work on implementing this one from the MSDN docs...

**Comment by AliceLR** [comment]
The original source of XAD's LZX decoder and pretty much all of the other (L)GPL ones appears to be a file called "unlzx.c", which is available on Aminet. While the XAD decoder doesn't credit it, it contains identical constructs to "unlzx.c" (including the same variable names and bitstream handling and weird buffer overrun hacks). "unlzx.c" contains no license in any form and may or may not even cite its original author. It *might* have been released as public domain (both are dated 1998), but I've seen cases where someone took ambiguously licensed code and slapped the GPL and their own copyright on it, so I'm assuming nothing. I'm going to continue writing a replacement.

**Comment by sezero** [comment]
> edit: also, the MSDN documentation for LZX is terrible and I've had to go back and forth between it and their later LZX DELTA documentation to figure out what it actually intended to say in places.

Possibly helpful: https://github.com/temisu/ancient

**Comment by AliceLR** [comment]
> > edit: also, the MSDN documentation for LZX is terrible and I've had to go back and forth between it and their later LZX DELTA documentation to figure out what it actually intended to say in places.
> 
> Possibly helpful: https://github.com/temisu/ancient

Thanks. Their LZX decompressor does seem to confirm some of the bizarre things I've been seeing with test inputs (and it's better to reference than LGPL or mystery license in this case). The delta packing seems to change between the literals and distances code blocks, and the "uncompressed" block type seems to actually be a CAB invention. It'd be nice if there was real documentation for this format somewhere.

**Comment by AliceLR** [comment]
My LZX depacker seems to work fine now. After some checking around I found a collection of MOD/MED/etc modules packed in LZX and it's clear that I'll *probably* need to implement support for merged files, a fixed 64k window version of 7z's solid compression.

libFuzzer/ASan hasn't found any issues yet, and performance comparisons at -O3 are looking favorable towards the new depacker (note: x86_64, so the new code might just be more vectorizable. Using `restrict` probably helps too. Also using a bit reversing table instead of individually reversing bits could be part of it).

It seems like libxmp's current depacker does not support merged files at all, despite unlzx.c supposedly supporting them. Someone also edited out support for stored files, despite them being fairly trivial to handle. The only LZX with a stored file I've seen is one I specifically instructed LZX to create though.

**Comment by AliceLR** [comment]
After a bit of fixing and cleanup and finally implementing merge support, I think the LZX depacker is *close* to ready. For now I'm just going to leave fuzzers running on it overnight and see if any more bugs show up. The decompression code has been tested against a variety of LZX files I've found around the web and currently will successfully unpack every archive I've used it on, so any further issues are probably merge related...

**Comment by AliceLR** [comment]
After looking at Lhasa a bit, its library is fairly sprawling compared to the XAD depacker, so just dropping it directly into src/depackers/ might not be the best option. Some thoughts:

* src/depackers/liblhasa/ I guess.
* Lhasa could be a soft external dependency for builds with depackers enabled. Similar to libunarr, liblhasa is available on most relevant Linux/etc distributions and should be easily portable for the ones it isn't on. I don't know how this impacts Amiga builds, though, and they probably need this format the most.
* Write another custom depacker for libxmp. LHA has much better documentation than the other depackers I've had to rewrite so far. I've looked at various specifications of the format and it doesn't seem *too* hard to write a custom depacker with the subset of LHA that libxmp needs. The last two have been a lot of work so I wouldn't get to this one right away, though.

**Comment by sezero** [comment]
> After looking at Lhasa a bit, its library is fairly sprawling compared to the XAD depacker, so just dropping it directly into src/depackers/ might not be the best option. Some thoughts:
> 
>     * src/depackers/liblhasa/ I guess.

Possibly, and with surgery to remove unnecessary parts of it

>     * Write another custom depacker for libxmp. LHA has much better documentation than the other depackers I've had to rewrite so far. I've looked at various specifications of the format and it doesn't seem _too_ hard to write a custom depacker with the subset of LHA that libxmp needs. The last two have been a lot of work so I wouldn't get to this one right away, though.

If you have the patience for it: The first option is the easiest, IMO.

**Comment by AliceLR** [comment]
Just LHA, BZip2, and Gzip to go. BZip2 is looking pretty close currently.
* #548

> > ```
> > * Write another custom depacker for libxmp.
> > ```
> If you have the patience for it: The first option is the easiest, IMO.

I do and I'm interested enough in the format I'd be willing to give it a shot. I'm not actually sure the first option is the easiest—stb_vorbis keeps reminding me that updating/patching contributed code that has been hacked up can also be a huge amount of effort.

Re: option 2, as mentioned in #538 there's libarchive, which has *much* better platform support than liblhasa. It mainly looks very promising for RAR, but is probably too sprawling to be anything but a dynamic linked external dependency. A smaller static linked/local option might still be better for LHA.

**Comment by sezero** [comment]
> Just LHA, BZip2, and Gzip to go. BZip2 is looking pretty close currently.

Just LHA and Gzip to go. Asked @cmatsuoka about gzip in private email.

**Comment by sagamusix** [comment]
No idea how accurate it is, but through [RP2040 Doom](https://kilograham.github.io/rp2040-doom/sound.html) I was just made aware that there has been a MIT-licensed OPL2 emulator the whole time! https://github.com/digital-sound-antiques/emu8950 - would require less porting effort than Opal if it's somewhat accurate.

**Comment by sezero** [comment]
Just LHA depacker and gunzip glue code to go.

@cmatsuoka: Is there any actual reason that the [gunzip glue code](https://github.com/libxmp/libxmp/blob/master/src/depackers/gunzip.c) to be under LGPL instead of MIT?

For the rest, i.e. the code not packaged in releases, I suggest moving them under an `attic` directory or similar?

**Comment by cmatsuoka** [comment]
I don't think there's any special reason for gunzip to be LGPL, the most
likely reason is that we forgot to relicense it. I'll create a quick PR to
address that.

**Comment by sezero** [comment]
OK, the gunzip PR is in.  Now the only thing left is lha depacker which there is an option of [lhasa](https://github.com/fragglet/lhasa) which requires some surgery on the existing library, or @AliceLR had an intention of writing one from scratch - don't know whether she still does.

**Comment by sezero** [comment]
Created PR #592 to move non-built and non-packaged dead under a `bitrot` directory. If someone can review it, we can merge.

**Comment by ccawley2011** [comment]
>     * The affected loaders might just as well be relicensed (or replaced if it comes to it).
>       
>       * `fcm_load.c` predates the Git repository. ProWizard supports this format so this can probably be junked.
>       * `ftm_load.c` predates the Git repository. (Also, it's not even close to finished.)
>       * `hvl_load.c` was [added in 2010](https://github.com/libxmp/libxmp/commit/37ff3c88e79475dd3b78070f10fe46d2fcdaff5a).
>       * `polly_load.c` was [added in 2010](https://github.com/libxmp/libxmp/commit/58a467a6b82c543e5a8f92a4618c7f9d943dc305).
>       * `ssmt_load.c` was [added in 2007](https://github.com/libxmp/libxmp/commit/4b27e63f2e9a0fd4d72601b4c49cd6e295e403b7).
>       * `stc_load.c` was [added in 2011](https://github.com/libxmp/libxmp/commit/10f92ec9f707fdef2ef893a388d79a39e81c60b4).

Is it still worth relicensing these files?

**Comment by sezero** [comment]
If we manage to replace the lha depacker properly which is the last one with LGPL, then there will be no need for two different release packages i.e. full and lite: After #594/#595 is done and lha handled, we can unify build and generate the two variants of the library from a single tarball _or_ from git.

**Comment by cmatsuoka** [comment]
Here it is: https://github.com/libxmp/libxmp/pull/591

**Comment by Wohlstand** [comment]
About the OPL3 support topic, and about the Opal thing: few minutes ago I fully converted it into the pure C, please review:
- https://github.com/Wohlstand/libADLMIDI/blob/master/src/chips/opal/opal.c [implementation]
- https://github.com/Wohlstand/libADLMIDI/blob/master/src/chips/opal/opal.h [header]

**Comment by AliceLR** [comment]
I think we should be good to go forward with this now?

**Comment by sezero** [comment]
> I think we should be good to go forward with this now?

Yes. Do you want to change the license or should I?

And we can also make the extra lite source packaging go away by adding a lite build option to autotools and cmake.

**Comment by sezero** [comment]
Created an `mit` branch in my fork: https://github.com/sezero/libxmp/tree/mit

If it looks good, we can merge that and mess with lite stuff later.
