### ISSUE TITLE
Tests don't have automatic dependency tracking

### ISSUE THREAD

**Issue by ccawley2011** [libxmp/libxmp#541]
This can cause confusion when rebuilding the tests after code in libxmp has changed.

**Comment by AliceLR** [comment]
Yeah, this is obnoxious. I *think* this should be adequate to fix it:

```diff
diff --git a/.gitignore b/.gitignore
index c0feddc4..b0220b33 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,4 +1,5 @@
 # Binaries
+*.d
 *.o
 *.lo
 *.so*
diff --git a/test-dev/Makefile.in b/test-dev/Makefile.in
index 70630378..2bdccfeb 100644
--- a/test-dev/Makefile.in
+++ b/test-dev/Makefile.in
@@ -8,7 +8,7 @@ V		= 0
 GCLIB		= libxmp-gc.a
 
 .c.o:
-	@CMD='$(CC) $(CFLAGS) -o $*.o $<'; \
+	@CMD='$(CC) -MD $(CFLAGS) -o $*.o $<'; \
 	if [ "$(V)" -gt 0 ]; then echo $$CMD; else echo CC $*.o ; fi; \
 	eval $$CMD
 
@@ -663,6 +663,8 @@ T_OBJS 		= $(addprefix $(TEST_PATH)/,$(TEST_OBJS)) \
 
 GCT_OBJS 	= $(addprefix $(TEST_PATH)/,$(TEST_OBJS))
 
+-include $(TESTS:=.d)
+
 default-test: check
 
 dist-test:
```

On the same note, maybe `depend` could go in the garbage while we're at it?

**Comment by AliceLR** [comment]
I finally realized that the reason clang periodically crashes with `make -j#` is that some instances of it are encountering an unfinished copy of all_tests.c. I did some very lazy benchmarking after revising this patch to fix that and to use `-MMD` instead of `-MD` and got this:

```
make clean && ./configure -C && time make -j8

Fedora before:
real	0m17.138s
real	0m16.519s
real	0m16.313s

Fedora -MMD:
real	0m16.786s
real	0m17.307s
real	0m16.732s

MSYS2 before:
real    0m36.378s
real    0m35.857s
real    0m36.030s

MSYS2 -MMD:
real    0m38.247s
real    0m38.061s
real    0m38.351s
```

So, it's only marginally slower in practice and I think things will be OK with this applied. (A significant portion of the MSYS2 slowness seems to be related to builds being unable to use all of my cores even with Defender turned off, so this +2s increase ends up not being very significant.)
