### ISSUE TITLE
How would I use libxmp in Unity?

### ISSUE THREAD

**Issue by RenegadeScooter** [libxmp/libxmp#587]
I'm a beginner developer, currently learning how to develop a game in Unity by developing a simple project that I plan to build upon later.

I really wanted to use some Creative-Commons-licensed tracker music composed by Andreas Viklund for my Unity project, and I decided to give this library a try because of its simple API. However, this library is coded in C and Unity uses C#, so I have to build the library into a .dll and then somehow get that running in Unity. Unity treats the .dll as a "native plugin," and the library contains several custom functions and data types.

How do I make this work?

**Comment by sezero** [comment]
You need to write your own C# bindings, I guess. (I don't know anything about C#, so I can't help.)

**Comment by AliceLR** [comment]
First off, I've never used C#, so I don't know what I'm talking about. I have marginal experience with the Java equivalent of this.

Right, you're going to have to add native function declarations to your class that interfaces with libxmp as described here: https://docs.unity3d.com/Manual/NativePlugins.html (note: don't statically link libxmp unless your software is GPL or LGPL or you're using libxmp-lite. This seems to only matter for iOS.)

Unfortunately, they don't provide much in terms of examples of how to do this, but they link to this MSDN document that seems like it should be useful: https://docs.microsoft.com/en-us/dotnet/framework/interop/marshalling-data-with-platform-invoke?redirectedfrom=MSDN

The C# native interface and libxmp's API makes this a little obnoxious because it seems that C# chars are 16-bits. The `xmp_context` used by most libxmp function calls is a `char *` typedef instead of `void *` (??), and the native interface maps C `char *` to C# `string`. You *might* have to force 8-bit char strings here. https://limbioliong.wordpress.com/2011/06/16/returning-strings-from-a-c-api/

If I'm interpreting this right you end up with something like:
```C#
[DllImport("libxmp", CharSet=CharSet.Ansi, CallingConvention=CallingConvention.StdCall)]
[return: MarshalAs(UnmanagedType.LPStr)]
private static extern string xmp_create_context();

[DllImport("libxmp", CharSet=CharSet.Ansi, CallingConvention=CallingConvention.StdCall)]
private static extern void xmp_free_context(string ctx);
```

This could be completely wrong, though. I asked in the MZX Discord server to see if anyone who actually knows what they're doing can help.

**Comment by SpudSupreme** [comment]
>I asked in the MZX Discord server to see if anyone who actually knows what they're doing can help.

Hear back from them yet? @AliceLR

**Comment by AliceLR** [comment]
No one responded either time I asked, sorry. :(

**Comment by sezero** [comment]
I _think_ this can be closed now.
