### ISSUE TITLE
Unify Spark and unix compress code?

### ISSUE THREAD

**Issue by ccawley2011** [libxmp/libxmp#617]
The [SparkFS manual](https://www.davidpilling.com/software/SparkFS.pdf) states that "Later versions of Spark, allowed not just crunch and squash, but also LZW with a larger number of bits "compress". This is like squash (just the same as the UNIX compress program) but can use between 12 and 16 bits.". This appears to correspond to `ARC_M_COMPRESSED` in libxmp's depacker code.

**Comment by sezero** [comment]
Haven't looked at anything, but -- @AliceLR?

**Comment by AliceLR** [comment]
I think this is a *bad idea*, not specifically for this case but because of the nature of LZW implementations in general. libxmp tried something like this before with ARC/Spark and Digital Symphony and it was not particularly maintainable. The main thing that I remember in ARC/ArcFS/Spark is they require input buffer hacks that I'm not sure would apply to Unix compress, but there were other hacks too I think.

This also wouldn't really reduce the executable size much:
```
$ cp src/depackers/uncompress.lo . && strip --strip-unneeded uncompress.lo && ls -l uncompress.lo
-rw-r--r-- 1 megazeux None 2285 Oct 22 16:51 uncompress.lo
```
```
$ cp src/depackers/arc_unpack.lo . && strip --strip-unneeded arc_unpack.lo && ls -l arc_unpack.lo
-rw-r--r-- 1 megazeux None 6933 Oct 22 16:52 arc_unpack.lo
```

**Comment by sezero** [comment]
Close ?

**Comment by AliceLR** [comment]
My comment doesn't have to be the final word on this or anything. If everyone generally agrees I think it's OK to close.

(On a similar note the Digital Symphony LZW and Sigma-Delta implementations should probably just be moved to the Digital Symphony loader so they can get streamlined and have proper 32-bit reads instead of alignment hacks.)

**Comment by sezero** [comment]
> My comment doesn't have to be the final word on this or anything. If everyone generally agrees I think it's OK to close.

@ccawley2011 ?

> 
> (On a similar note the Digital Symphony LZW and Sigma-Delta implementations should probably just be moved to the Digital Symphony loader so they can get streamlined and have proper 32-bit reads instead of alignment hacks.)

Sounds like a good idea to me.

**Comment by sezero** [comment]
> > My comment doesn't have to be the final word on this or anything. If everyone generally agrees I think it's OK to close.
> 
> @ccawley2011 ?

I'm guessing Cameron doesn't disagree -- closing.
