### ISSUE TITLE
STM mod plays incorrectly

### ISSUE THREAD

**Issue by divzilla** [libxmp/libxmp#769]
This mod plays incorrectly:
https://modland.com/pub/modules/Screamtracker%202/Purple%20Motion/emf%20-%20intro.stm

**Comment by AliceLR** [comment]
As mentioned in the Modland Discord server: this module *seems* to play fine and was likely affected by pre-4.6.0 bugs. The web player for which this module was reported broken also has broken Farandole Composer support, which was fixed in 4.6.0.

I will do some more testing tomorrow to figure out when exactly this was fixed (or if I'm missing something, but ST2 playback sounds more or less the same as libxmp).

**Comment by AliceLR** [comment]
Confirmed this bug was fixed in libxmp-4.5.0 by #92 (ca111900). With 4.4.1, several channels don't play at all.
