### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by AntonZab** [libxmp/libxmp#81]
In the winamp player witch in_xmp plugin is not played "axs" format file..... For axs format I have another plugin. When this plugin (in_axs) is one that axs files play fine. But when you add in_xmp plugin it captures this format and can not play the file. why is that?

**Comment by cmatsuoka** [comment]
Could you send me one of your axs files? Maybe xmp matches a file magic and thinks it's a module?

**Comment by AntonZab** [comment]
https://drive.google.com/file/d/0B0oEDro3cJx-bkpEYU92a0xBXzg/view?usp=sharing

**Comment by AliceLR** [comment]
I don't know if something has changed since 2016 (or whatever version of libxmp is used by in_xmp), but xmp currently does not load this module at all. This may be a bug in an older version of libxmp or a bug specifically in in_xmp.

**Comment by AliceLR** [comment]
> This is probably AXS from Resolution Audio thing:

Yes, that is the correct AXS as far as I know.

DOS versions on Modland: https://ftp.modland.com/pub/software/trackers/DOS/AXS/
Windows versions on Modland: https://ftp.modland.com/pub/software/trackers/Windows/AXS/

> As it seems, libxmp has never supported this: Closing now.

Correct. The issue was libxmp loading the file *despite* this, presumably as some other format e.g. one of the ProWizard formats. This apparently prevented the dedicated AXS plugin from loading it. libxmp does not load this module now and I don't know what changed.

> If there is interest in this in future, a new ticket should be created
> with format documentation.

That might be tricky because IIRC this format is fairly centered around software synthesis. I also don't know whether or not there's a format specification anywhere.

**Comment by sezero** [comment]
OK then, let's keep this one buried deep till eternity.
